zookeeper:
  image: trivadisbds/zookeeper
  container_name: zookeeper
  hostname: zookeeper
  net: bridge
  ports: 
    - "2181:2181"

nimbus:
  image: trivadisbds/storm-nimbus
  container_name: storm-nimbus
  hostname: storm-nimbus
  net: bridge
  ports:
    - "49773:49772"
    - "49772:49773"
    - "49627:49627"
  links:
    - zookeeper
  
supervisor:
  image: trivadisbds/storm-supervisor
  container_name: storm-supervisor
  hostname: storm-supervisor
  net: bridge
  ports:
    - "8000:8000"
  links:
    - zookeeper
    - nimbus
  
ui:
  image: trivadisbds/storm-ui
  container_name: storm-ui
  hostname: storm-ui
  net: bridge
  ports:
    - "49080:8080"
  links:
    - zookeeper
    - nimbus
  