zookeeper:
  image: trivadisbds/zookeeper
  ports: 
    - "2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.69.135
    KAFKA_DELETE_TOPIC_ENABLE: "true"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'    
    KAFKA_CREATE_TOPICS: "cra.status-stream-v3.avro:1:3,cra.status-stream-v4.avro:1:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
